// Secrets and vars that are set via `wrangler secret put` or the Cloudflare
// dashboard rather than declared in wrangler.jsonc — declared here so
// `worker-configuration.d.ts` can be regenerated by `wrangler types` without
// losing them.
declare namespace Cloudflare {
  interface Env {
    SLACK_APP_ID: string;
    SLACK_CLIENT_ID: string;
    SLACK_CLIENT_SECRET: string;
    SLACK_SIGNING_SECRET: string;
    SLACK_BOT_TOKEN: string;
    SLACK_CHANNEL_ID: string;
    DISCORD_PUBLIC_KEY: string;
    DISCORD_CLIENT_ID: string;
    DISCORD_CLIENT_SECRET: string;
    DISCORD_INVITE_URL: string;
    DISCORD_PERMISSIONS_INTEGER: string;
    DISCORD_TEST_GUILD_ID: string;
    DISCORD_TOKEN: string;
    DISCORD_WEBHOOK_URL: string;
    DISCORD_DIAGNOSTICS_WEBHOOK_URL: string;
    ADMIN_TOKEN: string;
  }
}
